import Head from 'next/head'
import Image from 'next/image'
import { getSession } from 'next-auth/react'
import  Navbar  from '../components/Navbar/Navbar.jsx'
import Login from './login'
import Leftbar from '../components/Leftbar/Leftbar.jsx'
import Feed from '../components/Feed/Feed'

export default function Home({session}) {

  if (!session){
    return(

      <Login />
      
    )
  }
  return (
    <div className='h-screen bg-gray-100 overflow-hidden'>
      <Head>
        <title>Socials.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className='flex'>

        {/* sidebar */}
        <Leftbar />
        {/* feed */}
        <Feed />
        {/* contacts */}

      </main>


    </div>
  )
}

export async function getServerSideProps(context){
    // Get user
    const session = await getSession(context);

    return{
      props:{
        session
      }
    }
}