import Head from 'next/head'
import Image from 'next/image'
import { getSession } from 'next-auth/react'
import  Navbar  from '../components/Navbar/Navbar.jsx'
import Login from './login'

export default function Home({session}) {

  if (!session){
    <Login />
  }
  return (
    <div>
      <Head>
        <title>Socials.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>

        {/* sidebar */}
        {/* feed */}
        {/* contacts */}

      </main>


    </div>
  )
}

export async function getServerSideProps(context){
    // Get user
    const session = await getSession(context);

    return{
      props:{
        session
      }
    }
}